CREATE TABLE USERS (
  NAME VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(128) NOT NULL,
  USERNAME VARCHAR(128) PRIMARY KEY,
  PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE USER_DATA (
  USERNAME VARCHAR(128) PRIMARY KEY,
  ABOUT VARCHAR(1000),
  DOB DATE,
  GENDER CHAR,
  LAST_MODIFIED TIMESTAMP,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE POSTS (
  POST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128),
  CREATED TIMESTAMP,
  CONTENT VARCHAR(1000),
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE NOTIFICATIONS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128),
  CREATED TIMESTAMP,
  CONTENT VARCHAR(1000),
  SEEN BOOLEAN,
  TYPE VARCHAR(128),
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE LIKES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  POST_ID BIGINT,
  USERNAME VARCHAR(128),
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE
);

CREATE TABLE COMMENTS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  POST_ID BIGINT,
  USERNAME VARCHAR(128),
  CONTENT VARCHAR(1000),
  CREATED TIMESTAMP,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE
);

CREATE TABLE SHARES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  POST_ID BIGINT,
  USERNAME VARCHAR(128),
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE
);

CREATE TABLE FRIENDS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128),
  FRIEND VARCHAR(128),
  SINCE TIMESTAMP,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (FRIEND) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE FRIEND_REQUESTS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REQUESTER VARCHAR(128),
  REQUESTEE VARCHAR(128),
  FOREIGN KEY (REQUESTER) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (REQUESTEE) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE MESSAGES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SENDER VARCHAR(128),
  RECEIVER VARCHAR(128),
  MESSAGE VARCHAR(1000),
  CREATED TIMESTAMP,
  SEEN BOOLEAN,
  FOREIGN KEY (SENDER) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (RECEIVER) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);